language: node_js
node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  yarn: true

deploy:
  - provider: script
    skip_cleanup: true
    script: ./publish.sh
    on:
      branch: master
